CREATE DATABASE Artistas;

USE Artistas;

CREATE TABLE Artistas
(
	idArtista INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL
);

CREATE TABLE Estilos
(
	idEstilo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL
);

CREATE TABLE Usuarios
(
	idUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Senha VARCHAR(50) NOT NULL,
	Permissao VARCHAR(50) NOT NULL
);

CREATE TABLE Albuns
(
	idAlbum INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(50) NOT NULL,
	dataLancamento DATETIME NOT NULL,
	Localizacao VARCHAR(50) NOT NULL,
	QuantidadeMinutos INT NOT NULL,
	AtivoVisualizacao BIT NOT NULL,
	idArtista INT FOREIGN KEY REFERENCES Artistas(idArtista)
);

CREATE TABLE AlbunsEstilos
(
	idAlbum INT FOREIGN KEY REFERENCES Albuns(idAlbum),
	idEstilo INT FOREIGN KEY REFERENCES Estilos(idEstilo)
);